# Generated by Django 5.0.6 on 2024-05-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=60)),
                ('uom', models.IntegerField()),
                ('price_per_unit', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('uom_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('uom_name', models.CharField(max_length=60)),
            ],
        ),
    ]
