# Generated by Django 5.0.6 on 2024-05-16 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.uom'),
        ),
    ]
