# Generated by Django 5.0.6 on 2024-05-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'product name'},
        ),
        migrations.AlterModelOptions(
            name='uom',
            options={'verbose_name': 'uom name'},
        ),
    ]
