# Generated by Django 5.0.6 on 2024-05-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_options_alter_uom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uom',
            options={'verbose_name': 'uom id'},
        ),
    ]
